//
// Created by 卢振鹏 on 2022/3/3.
//

#ifndef CPROGRAMMINGAMODERNAPPROACH_16_1READLINE_H
#define CPROGRAMMINGAMODERNAPPROACH_16_1READLINE_H

int read_line(char str[], int n);

#endif //CPROGRAMMINGAMODERNAPPROACH_16_1READLINE_H
